version: 3
images:
  base_image:
    name: fedora:latest
options:
  package_manager_path: /usr/bin/dnf
  tags:
    - my-ee
    - fedora
dependencies:
  python: requirements.txt
  galaxy: requirements.yml
  system: bindep.txt
additional_build_steps:
  prepend_base: |
    RUN dnf -y install sshpass python3 python3-devel python3-pip ansible jq git gcc libffi-devel openssl-devel
    RUN /usr/bin/python3 -m pip install --upgrade pip setuptools wheel
    RUN /usr/bin/python3 -m pip install --upgrade ansible-runner
