- name: Download the argo-cd manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: ~/install.yml
    mode: '0664'
- name: Applying the manifest to the cluster
  kubernetes.core.k8s:
    namespace: argocd
    state: present
    src: ~/install.yml
